### ISSUE TITLE
Not being returned to the web application after successful login on the CAS server

### ISSUE THREAD

**Issue by jseminck** [UniconLabs/cas-sample-java-webapp#1]
Hi,

With which version of CAS server is this supposed to work? I'm running CAS server 4.0 on my local host and am running into the following issue:
- I changed web.xml and refer all values to my local server
- I can build and deploy the web app without problems
- Going to the web app takes me to the following url on CAS:
  https://localhost:8443/cas/login?TARGET=https%3A%2F%2Flocalhost%3A8443%2Fcas-sample-java-webapp%2F
- After successful login, I stay on this URL and see the "successful" login screen from CAS -- so I am not being redirect back to the web application after successful login.

Audit log gives me this (sorry for the crappy layout)

2015-01-22 13:46:46,242 INFO [org.jasig.cas.authentication.PolicyBasedAuthenticationManager] - <SimpleTestUsernamePasswordAuthenticationHandler successfully authenticated User+password>
2015-01-22 13:46:46,242 DEBUG [org.jasig.cas.authentication.principal.PersonDirectoryPrincipalResolver] - <Attempting to resolve a principal...>
2015-01-22 13:46:46,242 DEBUG [org.jasig.cas.authentication.principal.PersonDirectoryPrincipalResolver] - <Creating SimplePrincipal for [User]>
2015-01-22 13:46:46,243 DEBUG [org.jasig.cas.authentication.PolicyBasedAuthenticationManager] - <org.jasig.cas.authentication.principal.PersonDirectoryPrincipalResolver@327dae65 resolved User from User+password>
2015-01-22 13:46:46,246 INFO [org.jasig.cas.authentication.PolicyBasedAuthenticationManager] - <Authenticated User with credentials [User+password].>
2015-01-22 13:46:46,246 DEBUG [org.jasig.cas.authentication.PolicyBasedAuthenticationManager] - <Attribute map for User: {uid=uid, eduPersonAffiliation=eduPersonAffiliation, groupMembership=groupMembership}>
2015-01-22 13:46:46,246 INFO [org.perf4j.TimingLogger] - <start[1421927206238] time[7] tag[AUTHENTICATE]>
#2015-01-22 13:46:46,247 INFO [com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN

WHO: audit:unknown
WHAT: supplied credentials: [User+password]
ACTION: AUTHENTICATION_SUCCESS
APPLICATION: CAS
WHEN: Thu Jan 22 13:46:46 EET 2015
CLIENT IP ADDRESS: 0:0:0:0:0:0:0:1
# SERVER IP ADDRESS: 0:0:0:0:0:0:0:1

> 2015-01-22 13:46:46,250 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Added ticket [TGT-1-ms17Ih751PPSRVpUxPqaEygdiknez9kvgv4mLYlCP3EdAtIqc0-cas01.example.org] to registry.>
> 2015-01-22 13:46:46,250 INFO [org.perf4j.TimingLogger] - <start[1421927206237] time[12] tag[CREATE_TICKET_GRANTING_TICKET]>
> # 2015-01-22 13:46:46,251 INFO [com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
> 
> WHO: audit:unknown
> WHAT: TGT-1-ms17Ih751PPSRVpUxPqaEygdiknez9kvgv4mLYlCP3EdAtIqc0-cas01.example.org
> ACTION: TICKET_GRANTING_TICKET_CREATED
> APPLICATION: CAS
> WHEN: Thu Jan 22 13:46:46 EET 2015
> CLIENT IP ADDRESS: 0:0:0:0:0:0:0:1
> # SERVER IP ADDRESS: 0:0:0:0:0:0:0:1
> 
> 2015-01-22 13:46:46,252 DEBUG [org.jasig.cas.web.support.CookieRetrievingCookieGenerator] - <Removed cookie with name [CASPRIVACY]>
> 2015-01-22 13:46:46,252 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Attempting to retrieve ticket [TGT-1-ms17Ih751PPSRVpUxPqaEygdiknez9kvgv4mLYlCP3EdAtIqc0-cas01.example.org]>
> 2015-01-22 13:46:46,253 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Ticket [TGT-1-ms17Ih751PPSRVpUxPqaEygdiknez9kvgv4mLYlCP3EdAtIqc0-cas01.example.org] found in registry.>
> 2015-01-22 13:46:46,253 DEBUG [org.jasig.cas.web.support.CookieRetrievingCookieGenerator] - <Added cookie with name [CASTGC] and value [TGT-1-ms17Ih751PPSRVpUxPqaEygdiknez9kvgv4mLYlCP3EdAtIqc0-cas01.example.org]>
> 2015-01-22 13:46:46,263 DEBUG [org.jasig.cas.web.support.CasArgumentExtractor] - <Extractor did not generate service.>

I'm pretty new to CAS and it's a little overwhelming :) I may have missed some setup somewhere... any help is much appreciated.

Thanks

**Comment by jseminck** [comment]
After changing the web.xml config to the following (comment the Saml11AuthenticationFilter and uncomment the AuthenticationFilter) then the redirect works fine, but the user name returned is set to NULL

		<filter-name>CAS Authentication Filter</filter-name>
		
		<filter-class>org.jasig.cas.client.authentication.AuthenticationFilter</filter-class>

Authenticated User Id: null
The user principal is empty from the request object. Review the wrapper filter configuration.

**Comment by plotters** [comment]
I just noticed that when Saml1Authentication filter is changed to AuthenticationFilter it starts to redirect. Cannot get user credentials though...

<filter>
        <filter-name>CAS Authentication Filter</filter-name>
        
         <filter-class>org.jasig.cas.client.authentication.AuthenticationFilter</filter-class>
