### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by morteza57** [UniconLabs/cas-sample-java-webapp#4]
When i login in the logging page and want to redirect it to the index.jsp the error 404 appeared that tell me the resource doesn't exist.

**Comment by mmoayyed** [comment]
You cannot go to index.jsp. The app will auto-redirect. You should just simply point your browser to http://<server-name>:<port>/<app-name> which might be http://localhost:8080/cas-sample-java-webapp

If you can't get there, it means the app has crashed and there is a problem somewhere in your config.

**Comment by morteza57** [comment]
i set this https://localhost:8443/cas/login in my web.xml what is the problem that i can not see the index.jsp
